# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 9) do

  create_table "open_id_authentication_associations", :force => true do |t|
    t.column "server_url", :binary
    t.column "handle",     :string
    t.column "secret",     :binary
    t.column "issued",     :integer
    t.column "lifetime",   :integer
    t.column "assoc_type", :string
  end

  create_table "open_id_authentication_nonces", :force => true do |t|
    t.column "nonce",   :string
    t.column "created", :integer
  end

  create_table "open_id_authentication_settings", :force => true do |t|
    t.column "setting", :string
    t.column "value",   :binary
  end

  create_table "photos", :force => true do |t|
    t.column "place_id",     :integer
    t.column "user_id",      :integer
    t.column "parent_id",    :integer
    t.column "content_type", :string
    t.column "filename",     :string
    t.column "thumbnail",    :string
    t.column "size",         :integer
    t.column "width",        :integer
    t.column "height",       :integer
    t.column "created_at",   :datetime
    t.column "updated_at",   :datetime
  end

  create_table "places", :force => true do |t|
    t.column "title",       :string
    t.column "lat",         :decimal,  :precision => 15, :scale => 10
    t.column "lng",         :decimal,  :precision => 15, :scale => 10
    t.column "user_id",     :integer
    t.column "telephone",   :string
    t.column "description", :text
    t.column "created_at",  :datetime
    t.column "updated_at",  :datetime
    t.column "address",     :string
  end

  create_table "users", :force => true do |t|
    t.column "login",                     :string
    t.column "email",                     :string
    t.column "crypted_password",          :string,   :limit => 40
    t.column "salt",                      :string,   :limit => 40
    t.column "created_at",                :datetime
    t.column "updated_at",                :datetime
    t.column "last_login_at",             :datetime
    t.column "remember_token",            :string
    t.column "remember_token_expires_at", :datetime
    t.column "visits_count",              :integer,                :default => 0
    t.column "identity_url",              :string
    t.column "read_intro",                :boolean,                :default => false
  end

end
